spring.application.name=gadei-core-backend
spring.datasource.url=jdbc:mysql://localhost:3306/yagamistore
spring.datasource.username=root
spring.datasource.password=kaday228686
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql

spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-methods=*
spring.graphql.cors.allowed-headers=*