spring.application.name=gadei-core-backend
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/yagamistore}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:kaday228686}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql

spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-methods=*
spring.graphql.cors.allowed-headers=*