-- ==========================================
-- PostgreSQL data.sql
-- ==========================================

DROP TABLE IF EXISTS pic_ref CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS title_ref CASCADE;
DROP TABLE IF EXISTS account CASCADE;

-- ==========================================
-- TABLES
-- ==========================================

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    category_id BIGINT,
    CONSTRAINT fk_genre_category
        FOREIGN KEY (category_id)
        REFERENCES category(id)
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255),
    name VARCHAR(255),
    image_url VARCHAR(255),
    price DOUBLE PRECISION,
    quantity INTEGER,
    discount DOUBLE PRECISION,
    genre_id BIGINT,
    CONSTRAINT fk_product_genre
        FOREIGN KEY (genre_id)
        REFERENCES genre(id)
);

CREATE TABLE title_ref (
    syskey BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    valid_from DATE,
    expire_at DATE
);

CREATE TABLE pic_ref (
    syskey BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url VARCHAR(255),
    title_syskey BIGINT,
    product_id BIGINT,

    CONSTRAINT fk_picref_title
        FOREIGN KEY (title_syskey)
        REFERENCES title_ref(syskey),

    CONSTRAINT fk_picref_product
        FOREIGN KEY (product_id)
        REFERENCES product(id)
);

CREATE TABLE account (
    email VARCHAR(255) PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP
);

-- Product
INSERT INTO product
(id,code,name,image_url,price,quantity,discount,genre_id)
VALUES

(1,'TSST001','My Hero Academia','as10.png',3300,50,0,1),
(2,'TSST002','Kimetsu No Yaiba - Nezuko','as2.png',3200,50,0,1),
(3,'TSST003','Shingeki No Kyojin - Eren','as3.png',3250,50,0,1),
(4,'TSST004','Jujutsu Kaisen - Gojo','as4.png',2800,50,0,1),
(5,'TSST005','One Piece - Luffy','as5.png',3300,50,0,1),
(6,'TSST006','Naruto','as6.png',3500,50,0,1),
(7,'TSST007','Itachi','as7.png',3600,50,0,1),
(8,'TSST008','Naruto & Sasuke','as8.png',3400,50,0,1),
(9,'TSST009','Kimetsu No Yaiba - Duo Moon','as9.png',3200,50,0,1),

(10,'TSPL001','Polo Gray','pl1.png',4300,50,0,2),
(11,'TSPL002','Polo Navy','pl2.png',4300,50,0,2),
(12,'TSPL003','Polo White-Yellow','pl3.png',4300,50,0,2),
(13,'TSPL004','Polo White-Gray','pl4.png',4300,50,0,2),

(14,'JELR001','Baggy Wide Leg','baggy_wide_leg.png',3600,50,0,3),
(15,'JELR002','Bootcut Flare','bootcut_flare.png',3600,50,0,3),
(16,'JELR003','Straight','straight.png',3600,50,0,3),
(17,'JELR004','Skinny','skinny.png',3600,50,0,3),
(18,'JELR005','Jeanskirt','jeanskirt.png',3100,50,0,3),

(19,'JEJK001','Jean Jacket','jacket.png',3600,50,0,4);

-- PicRef
INSERT INTO pic_ref
(syskey,image_url,title_syskey,product_id)
VALUES

-- Event Slides
(1,'slide1.png',1,NULL),
(2,'slide2.png',1,NULL),
(3,'slide3.png',1,NULL),
(4,'slide4.png',1,NULL),

-- Trending Products
(5,NULL,2,7),
(6,NULL,2,14),
(7,NULL,2,19),
(8,NULL,2,13),
(9,NULL,2,9),
(10,NULL,2,15),
(11,NULL,2,11);

-- TitleRef
INSERT INTO title_ref (syskey, name, valid_from, expire_at)
VALUES
(1,'Event','2026-01-01','2026-12-31'),
(2,'Trend','2026-01-01','2026-12-31');

-- Category
INSERT INTO category(name)
VALUES
('T-Shirt'),
('Jean'),
('Pants'),
('Blouse'),
('Sneaker'),
('Shoes');

-- Genre
INSERT INTO genre(name, category_id)
VALUES
('Sticker',1),
('Polo',1),
('Low-Rise',2),
('Jacket',2);

-- ==========================================
-- RESET IDENTITY SEQUENCES
-- ==========================================

SELECT setval(pg_get_serial_sequence('category','id'),
              (SELECT MAX(id) FROM category));

SELECT setval(pg_get_serial_sequence('genre','id'),
              (SELECT MAX(id) FROM genre));

SELECT setval(pg_get_serial_sequence('product','id'),
              (SELECT MAX(id) FROM product));

SELECT setval(pg_get_serial_sequence('title_ref','syskey'),
              (SELECT MAX(syskey) FROM title_ref));

SELECT setval(pg_get_serial_sequence('pic_ref','syskey'),
              (SELECT MAX(syskey) FROM pic_ref));