
type Category  {
    id: ID
    name: String
    bannerImageUrl: String
    genres: [Genre]
}

type Genre {
    id: ID
    name: String
    category: Category
}

type Product {
    id: ID
    code: String
    name: String
    imageUrl: String
    price: Float
    quantity: Int
    discount: Float
    genre: Genre
    category: Category
}

type TitleRef {
	syskey: Int
	name: String
}

type PicRef {
	syskey: Int
	imageUrl: String
	title: TitleRef
	product: Product
}

type CartItem {
    productId: ID
    productImage: String
    productName: String
    price: Float
    quantity: Int
}

input CartItemInput {
    productId: ID
    productImage: String
    productName: String
    price: Float
}

input ProductUploadDTO {
    code: String
    name: String
    imageUrl: String
    price: Float
    quantity: Int
    discount: Float
    genre_id: Int
}

input FilterInput {
    itemid: ID!
    caption: String
    fieldname: String
    datatype: String
    condition: String
    value: String
    value2: String
}

input FilterDatasetInput {
    filterList: [FilterInput!]!
}

type Game {
    id: ID
    name: String
    logo: String
    imageUrl: String
    downloadUrl: String
    items: [Item]
}

type Item {
    id: ID
    name: String
    quantity: Float
    bonus: Float
    price: Float
    imageUrl: String
    game: Game
}

type Payment {
    id: ID
    name: String
    imageUrl: String
}

type Server {
    id: ID
    name: String
}

type Slip {
    uid: ID
    serverName: String
    itemName: String
    paymentName: String
    quantity: Float
    price: Float
}

enum Role {
    USER
    ADMIN
}

type Account {
    email: String!
    fullName: String!
    phoneNumber: String!
    role: Role!
    createdAt: String!
}

type JwtRespDTO {
    token: String!
    token_type: String!
}

input TopupInput {
  uid: ID
  serverId: Int
  itemId: Int
  paymentId: Int
  email: String
}

input SignInForm {
    email: String!
    password: String!
}

input SignUpForm {
    email: String!
    password: String!
    fullName: String!
    phoneNumber: String!
}

type Query {
    allCategories: [Category]
    categoryById(id: ID): Category

    allGenres: [Genre]
    genresByCategoryId(id: ID): [Genre]
    genreById(id: ID): Genre

    allProducts: [Product]
    productsByGenreId(id: ID): [Product]
    productsByText(searchText: String, categoryId: ID): [Product]
    filterProducts(filterDataset: FilterDatasetInput!, categoryId: ID!): [Product]
    productById(id: ID): Product

    cartSize: Int
    cartPrice: Float
    allCartItems: [CartItem]
    
    eventSliders: [PicRef]
    trendings: [PicRef]
    
    allGames: [Game]
    searchGames(searchText: String): [Game]
    getGameById(id: ID): Game
    allItemsByGameId(id: ID): [Item]
    allPayments: [Payment]
    allServers: [Server]
    
}

type Mutation{
    addToCart(cartItem: CartItemInput): Int
    removeFromCart(cartItem: CartItemInput): Int
    removeCertainItem(cartItem: CartItemInput): Int
    uploadProduct(product: ProductUploadDTO): Int
    checkout(topup: TopupInput): Slip
    signIn(signInForm: SignInForm): JwtRespDTO
    signUp(signUpForm: SignUpForm): JwtRespDTO
}

